name: metgo_components
description: description goes here
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  metgo_resources: any
  go_router: ^11.1.3

  vector_graphics: ^1.1.7
  google_maps_flutter: ^2.5.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
